FROM ct2034/vnc-ros-kinetic-full

COPY . ~/

RUN sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5

RUN sudo apt update
RUN sudo apt upGRADE

RUN sudo apt-get install checkinstall ros-kinetic-catkin python-catkin-tools


